<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Calendly</name>
   <tag></tag>
   <elementGuidId>52584280-cb79-46d2-bd53-d8e72ee8d003</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d3v0px0pttie1i.cloudfront.net/uploads/user/avatar/596022/00004252.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Avatar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_36ich___index-Avatar__cls1 _20fGW___index-Avatar__sidebarView _2iwMh___index-Avatar__isDesktopUp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-region&quot;)/div[@class=&quot;_3i0k6___Layout__cls1&quot;]/div[@class=&quot;_2LpwQ___Wrapper__cls1 _1cMla___Wrapper__media-tablet-up _1P3Wz___Wrapper__media-desktop-up&quot;]/div[@class=&quot;_36Zc1___container-StyledContainer__cls1 _1WIQY___container-StyledContainer__isTabletUp _3yQXt___container-StyledContainer__isDesktopUp&quot;]/div[@class=&quot;_1x5lK___side_panel-Panel__cls1 _2rtAw___side_panel-Panel__isDesktopUp&quot;]/div[@class=&quot;_3Fp1z___side_panel-Container__cls1 gjDtZ___side_panel-Container__isDesktopUp&quot;]/div[@class=&quot;_3zPIm___side_panel-ScrollContainer__cls1&quot;]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/div[@class=&quot;_2DyJO___side_panel-InnerPaddingContainer__cls1&quot;]/div[@class=&quot;_3Kp-3___index-Container__cls1&quot;]/img[@class=&quot;_36ich___index-Avatar__cls1 _20fGW___index-Avatar__sidebarView _2iwMh___index-Avatar__isDesktopUp&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SPACETIME API/ADMIN/PopUp/Calendy_popUp</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-region']/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Avatar']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
