<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Comparison Table</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>edc92ac2-b613-46cc-b19a-f56f98f748b1</testSuiteGuid>
   <testCaseLink>
      <guid>aa35d844-cee6-4bc7-903e-a255cb7d5c6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/CONSUMER/Consumer Login Non Private</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>da6ed82b-7e03-484e-a685-5ab3807005ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison Table/navigate_ComparisonTable</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>353a8e1b-8ab4-4cc1-8183-1bcffadc8186</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison List/01_searchItemName</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c2aa810f-0f5c-4db0-9c3d-3499f7f9a3f6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/SearchResult</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>c2aa810f-0f5c-4db0-9c3d-3499f7f9a3f6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemName</value>
         <variableId>5b72cd56-376a-41af-bc78-2bcfa65450c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2aa0c8f-8d3c-4da1-9190-495f2c917888</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison List/02_searchCustomField</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dcb1295f-28cf-4cbd-b4d4-3c3bee26efdb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/SearchResult</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>dcb1295f-28cf-4cbd-b4d4-3c3bee26efdb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemCustomField</value>
         <variableId>8b631c10-3a41-4e1f-ae80-739c68290b21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dcb1295f-28cf-4cbd-b4d4-3c3bee26efdb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemName</value>
         <variableId>0d3d3e65-b34c-4966-bda7-0dff6f888aae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51982363-92dc-43a3-a0e1-1e26ff636908</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison List/03_searchPartialItemName</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7ed73d93-5c08-47ca-a3b9-ea20d7a8e3d2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/SearchResult</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>7ed73d93-5c08-47ca-a3b9-ea20d7a8e3d2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemNamePartial</value>
         <variableId>e58d1eaf-5264-4246-9b48-8d5c78b6fa8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7ed73d93-5c08-47ca-a3b9-ea20d7a8e3d2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemName</value>
         <variableId>573cfa98-0d88-4a1f-9a4d-1072e59172ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1e1f895-8728-4328-abf2-9fd54188eff5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison List/04_searchPartialCustomFields</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ea0307a4-6287-452d-8d49-48e88812ff42</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/SearchResult</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ea0307a4-6287-452d-8d49-48e88812ff42</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemCustomFieldPartial</value>
         <variableId>42044fe7-8bd5-4e30-9b6a-53718e1fd6c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ea0307a4-6287-452d-8d49-48e88812ff42</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemName</value>
         <variableId>56dc7df2-ab1a-4e43-b21d-40f2497fd7ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9895e5e8-39f0-4e2e-ac14-d1cdfedc33bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison List/05_itemNameCategory</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>719316ad-7a53-4178-b582-6b815543379a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/SearchResult</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>719316ad-7a53-4178-b582-6b815543379a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemNameCategory</value>
         <variableId>71ebdc17-14dc-4527-8646-a4f961492272</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>719316ad-7a53-4178-b582-6b815543379a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>9a9d9316-2eab-4bf0-9205-072d5179ae34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>26f16bc8-f8b8-46f8-b84f-858552c5ecbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison List/06_customFieldCategory</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>efa4a3ce-3556-4ea8-912a-f88be61c338a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/SearchResult</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>efa4a3ce-3556-4ea8-912a-f88be61c338a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemCustomField</value>
         <variableId>6d9c9c89-86db-45cd-85a0-ae26d19f784d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>efa4a3ce-3556-4ea8-912a-f88be61c338a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>ff1ae086-4c67-4ce2-8ab7-dc7e2283add2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>efa4a3ce-3556-4ea8-912a-f88be61c338a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemNameCategory</value>
         <variableId>9cb90836-503d-4e8d-99f7-54bb081e8b4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a07aefe6-fcfe-487d-bbe1-9e005f2c1e99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison List/07_itemNamePartialCategory</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6b46bd10-0624-4ed8-8aa8-ef2be2edaa01</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/SearchResult</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>6b46bd10-0624-4ed8-8aa8-ef2be2edaa01</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemNamePartial</value>
         <variableId>effdda82-1bd1-4ea4-91fb-ae90f3b45591</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6b46bd10-0624-4ed8-8aa8-ef2be2edaa01</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>441d8291-c76b-4073-9c1c-fcf3b75eef22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6b46bd10-0624-4ed8-8aa8-ef2be2edaa01</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemNameCategory</value>
         <variableId>e0a7b3d3-0f97-41b2-9da7-e23a33405f14</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51413a95-78e9-4c5a-9bfa-77c3240dc642</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison List/08_customFieldPartialCategory</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fade2af6-668c-4d11-96b4-adc7324b4b08</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/SearchResult</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>fade2af6-668c-4d11-96b4-adc7324b4b08</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemCustomFieldPartial</value>
         <variableId>3b58791f-596c-4186-a1f2-db38ff640269</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fade2af6-668c-4d11-96b4-adc7324b4b08</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>59098cbf-1a37-45d5-9abe-59d5811ee5d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fade2af6-668c-4d11-96b4-adc7324b4b08</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemNameCategory</value>
         <variableId>e8c7508f-eefd-4ecf-bba2-a303a3ee7860</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abaa5849-0f58-4ded-9d4f-9521e9c9954d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison List/09_BlankSearch</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0b325bd5-5207-4a25-b31e-1ddd00c25225</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/SearchResult</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0b325bd5-5207-4a25-b31e-1ddd00c25225</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemNameRecent</value>
         <variableId>00f027e2-4261-423b-9fc7-bd46dbe5cc49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a67a45bc-862a-409e-b922-ea4e1b0c1b8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Comparison List/10_searchCategoryOnly</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>235bc755-46f5-4064-bf1b-869ad1da312d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/SearchResult</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>235bc755-46f5-4064-bf1b-869ad1da312d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>f2c63f0a-8e78-4acf-8dee-072af3d5d9f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>235bc755-46f5-4064-bf1b-869ad1da312d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemName</value>
         <variableId>d92cb445-9a9d-4f51-8166-0b074d73cf78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>453e81f0-932a-4cdd-8a25-a5d4783c7b14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
