<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Purchase History Details</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1ffa9ebf-3d61-4010-85a3-3d0f205aa2f6</testSuiteGuid>
   <testCaseLink>
      <guid>aa12b424-5499-4aae-84c5-8456e303919a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/CONSUMER/Consumer Login Non Private</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0cb5546d-6530-4c3f-899e-372803c3faf5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/navigate_PurchaseHistoryDetails</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>044ecdce-506d-4400-8fa0-db95f876642c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/01_searchItemName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19851041-2082-4bcc-a914-aa34af356fd2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3b458fe-dbcb-4fce-a2f0-a5ee6ef2185a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/02_searchItemDescription</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9202d35-cbe4-491f-9700-5d7fe6f9a080</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55d1d22d-87a1-40da-a55a-3799543a7a6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3dc67bb5-4c9e-4da2-8fba-90fdf5c5ceee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/04_searchPartialItemName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8b90a2e-0a17-429f-a44d-e0822261b9ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b6a57a2-d094-4e26-91a5-37979903b817</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89882807-a8e0-4d52-8672-9a1bd87e1099</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/05_searchPartialItemDescription</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e07c328-9580-4c01-85c8-56abf9ce73be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d21ad3ca-711d-4304-bde5-19472429f9ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4f10915-8bfe-4f40-8883-47000ad3c1d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/07_itemNameCategory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adeb4ebf-1f10-4383-bdbc-694338a4c878</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e99f65ea-d3c8-443a-b6ef-9ec127ed6c6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b2eb2790-3c10-41dd-8b10-5c4400e92006</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/08_itemDescCategory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b35f1b0-450c-4fad-98cd-734da94a9dae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6623ff80-fe97-41ab-8b5d-fbc829ca90d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea28954d-65b9-4d5f-99bf-94fd22d49e6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8cdaae97-96a6-47ce-9f04-971b51d37542</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/10_itemNamePartialCategory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c2db410-fbb7-4ea0-8557-7a7c69c274f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac1bc718-e96d-43d7-a4d4-e89203971dfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2334075b-45d7-41b3-b191-423b0f926b15</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b32b465f-fbdb-4aaf-835b-20f63c4eaf16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/11_itemDescPartialCategory</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73df34c3-56a8-4c76-8f25-be73e9f38066</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>267f4c1c-79fe-47a2-b868-0b3087f01af0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfd42cb-0a13-400c-84ca-e81faf82d1be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec86ed8b-4726-4912-b7ef-28a523cd5dec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/13_searchCategoryOnly</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9d21c25-7333-4498-b771-35f398839eeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3913d7f5-1f3b-4ec9-88ad-764b8b7c29b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4857309-7d16-4cdc-9238-36f9e9052b9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Search Result Page/Search per Page/Purchase History Details/14_BlankSearch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30ff4c3a-ba69-4894-a646-e09f48322325</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d80009f1-0a3e-41c5-a44b-3f28d76eac5b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
