<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_info</name>
   <tag></tag>
   <elementGuidId>1c144da0-6cbd-4716-892a-df0472751d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.delete-item > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbl-terms']/tbody/tr/td[4]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/delete_btn.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl-terms&quot;)/tbody[1]/tr[@class=&quot;item-temp-1625639266415&quot;]/td[4]/a[@class=&quot;delete-item&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbl-terms']/tbody/tr/td[4]/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a/img</value>
   </webElementXpaths>
</WebElementEntity>
