<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkunli1</name>
   <tag></tag>
   <elementGuidId>6c37260a-bd40-46bd-8fbc-b274adc8ce4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;pricing_tab&quot;]/div[2]/div/div/div[2]/div[3]/div[4]/table/tbody/tr[1]/td[10]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;pricing_tab&quot;]/div[2]/div/div/div[2]/div[3]/div[4]/table/tbody/tr[1]/td[10]/div/label</value>
   </webElementProperties>
</WebElementEntity>
