<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cb_availableShipping</name>
   <tag></tag>
   <elementGuidId>74aacbcf-cb86-4bd4-ae54-97f279960479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.check-box.available > span > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblDelivery']/thead/tr/th[3]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>checkDeliveryAll</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblDelivery&quot;)/thead[1]/tr[1]/th[@class=&quot;check-box available&quot;]/span[1]/label[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblDelivery']/thead/tr/th[3]/span/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/span/label</value>
   </webElementXpaths>
</WebElementEntity>
