<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_SelectAllOrderStatus</name>
   <tag></tag>
   <elementGuidId>ba2dce1a-5c9b-49c5-9ef8-41822d47807f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[1]/div[2]/div/div/div/div[2]/form/div/div[1]/div/div/div/span[3]/div/div/ul/li[2]/a/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
