<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_seller01</name>
   <tag></tag>
   <elementGuidId>0533cb89-86ba-4ea8-bbdb-2ddded9be13f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[1]/div[2]/div/div/div/div[2]/form/div/div[1]/div/div/div/span[2]/div/div/ul/li[4]/a/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
