<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_seller03</name>
   <tag></tag>
   <elementGuidId>ff10914c-21bb-4350-930b-91864a9a373a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[1]/div[2]/div/div/div/div[2]/form/div/div[1]/div/div/div/span[2]/div/div/ul/li[5]/a/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
