<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>category1percent</name>
   <tag></tag>
   <elementGuidId>8bb8ab29-27d1-4cc8-9caa-6073a27dbf6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[8]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div[1]/div[3]/div[1]/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[8]/label</value>
   </webElementProperties>
</WebElementEntity>
