<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_seller</name>
   <tag></tag>
   <elementGuidId>0904ab90-8b6f-4cde-9049-2b4c55e8520c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store-container']/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://0407bpth2.test.arcadier.io/images/user/26a5867f-2595-48ab-8ca3-f02d73e399c2-yhynw8t9gpwhite-and-pink-flowerson-a-book-beside-eyeglasses-545042.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store-container&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;store-detail-box&quot;]/div[@class=&quot;thumb-outer&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='store-container']/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://0407bpth2.test.arcadier.io/images/user/26a5867f-2595-48ab-8ca3-f02d73e399c2-yhynw8t9gpwhite-and-pink-flowerson-a-book-beside-eyeglasses-545042.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
