<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slider</name>
   <tag></tag>
   <elementGuidId>9076500a-5277-4a94-8270-527282f2b82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page-region&quot;]/div/div/div/div[1]/div/div/div[1]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page-region&quot;]/div/div/div/div[1]/div/div/div[1]/div[2]/div/div/div/div</value>
   </webElementProperties>
</WebElementEntity>
