<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_Email_email</name>
   <tag></tag>
   <elementGuidId>5d9c126b-a39d-4e88-86f6-df2223fbb6e2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kind</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3KAjx___index-Component__cls1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-region&quot;)/div[@class=&quot;_3i0k6___Layout__cls1&quot;]/div[@class=&quot;_2LpwQ___Wrapper__cls1 _1cMla___Wrapper__media-tablet-up _1P3Wz___Wrapper__media-desktop-up&quot;]/div[@class=&quot;_36Zc1___container-StyledContainer__cls1 _3Atqo___container-StyledContainer__expanded _1WIQY___container-StyledContainer__isTabletUp _3yQXt___container-StyledContainer__isDesktopUp&quot;]/div[@class=&quot;_11234___MainPanel__cls1 _2AWMg___MainPanel__isDesktopUp&quot;]/div[@class=&quot;_1dX2m___ContentWrapper__cls1 _1W4fH___ContentWrapper__isTabletUp&quot;]/div[@class=&quot;H2Xvx___DetailsForm__cls1&quot;]/form[1]/div[@class=&quot;mbl&quot;]/fieldset[@class=&quot;_3rBcz___Fieldset__cls1&quot;]/div[@class=&quot;_2py84___invitee_inputs-TextField__cls1&quot;]/label[@class=&quot;_3Hc0u___index-Label__cls1&quot;]/div[@class=&quot;O2xxi___TextInput__cls1&quot;]/input[@class=&quot;_3KAjx___index-Component__cls1&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SPACETIME API/ADMIN/PopUp Calendly_Subscription/iframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-region']/div/div/div/div[2]/div/div/form/div/fieldset/div[2]/label/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/div/input</value>
   </webElementXpaths>
</WebElementEntity>
