<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_24h</name>
   <tag></tag>
   <elementGuidId>44240463-429e-4e11-8d31-c67e29e19135</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NGlWd___switch_field-Label__cls1 _2y7Xb___switch_field-Label__isClickable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24h</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-region&quot;)/div[@class=&quot;_3i0k6___Layout__cls1&quot;]/div[@class=&quot;_2LpwQ___Wrapper__cls1 _1cMla___Wrapper__media-tablet-up _1P3Wz___Wrapper__media-desktop-up&quot;]/div[@class=&quot;_36Zc1___container-StyledContainer__cls1 _1WIQY___container-StyledContainer__isTabletUp _3yQXt___container-StyledContainer__isDesktopUp&quot;]/div[@class=&quot;_11234___MainPanel__cls1 _2AWMg___MainPanel__isDesktopUp&quot;]/div[@class=&quot;_2Mxry___spotpicker-Wrapper__cls1 _3nTTH___spotpicker-Wrapper__isTabletUp&quot;]/div[@class=&quot;_2o65w___spotpicker-Row__cls1 bWMEJ___spotpicker-Row__isDesktopUp _3xF-4___spotpicker-Row__isTabletUp&quot;]/div[@class=&quot;_2NS5____dates-Wrapper__cls1 _2V91H___dates-Wrapper__isTabletUp&quot;]/div[@class=&quot;_1198f___dates-CalendarContainer__cls1&quot;]/div[@class=&quot;LnCW____timezone-Container__cls1 _1OH5H___timezone-Container__isTabletUp&quot;]/div[@class=&quot;_1b3GR___index-Container__cls1&quot;]/div[@class=&quot;_1kDUF___picker-Container__cls1 Afqtq___container-TimezoneContainer__cls1 _1r_-P___popup_dropdown_menu-Container__cls1 _2lESb___Menu__cls1 _1f_mO___fixed-container-Container__cls1&quot;]/div[@class=&quot;_2S7ur___picker-SwitcherContainer__cls1&quot;]/div[@class=&quot;QCLk9___switch_field-Container__cls1&quot;]/label[@class=&quot;NGlWd___switch_field-Label__cls1 _2y7Xb___switch_field-Label__isClickable&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/SPACETIME API/ADMIN/PopUp Calendly_Subscription/iframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-region']/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div[2]/label[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='am/pm'])[1]/following::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time zone'])[1]/following::label[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='US/Canada'])[1]/preceding::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24h']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
   </webElementXpaths>
</WebElementEntity>
