<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_sellerDisplayName</name>
   <tag></tag>
   <elementGuidId>fb261278-36f3-47d9-b5ed-3b9bff4c24f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div/div/div/section[3]/div/div/div[5]/div/div[1]/table/tbody/tr[2]/td/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/div/div/section[3]/div/div/div[5]/div/div[1]/table/tbody/tr[2]/td/span[1]</value>
   </webElementProperties>
</WebElementEntity>
