<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_delete sub</name>
   <tag></tag>
   <elementGuidId>df8da2ca-9c7c-4c69-bcf8-b21fe4f128c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div[1]/div/div/div[3]/table/tbody/tr[2]/td[5]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div[1]/div/div/div[3]/table/tbody/tr[2]/td[5]/a/i</value>
   </webElementProperties>
</WebElementEntity>
