<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_city state</name>
   <tag></tag>
   <elementGuidId>01a1f8f5-62f3-4c57-ac6a-c2a1861e113a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[1]/div[2]/div/div/div[2]/div[2]/div/div[4]/div[2]/div[1]/div[1]/span/p[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[1]/div[2]/div/div/div[2]/div[2]/div/div[4]/div[2]/div[1]/div[1]/span/p[4]</value>
   </webElementProperties>
</WebElementEntity>
