<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_shipping Name</name>
   <tag></tag>
   <elementGuidId>4f0c810e-70aa-4d85-91a9-dbc2629e74b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div/div/div/section[3]/div/div/div[5]/div/div[2]/table/tbody/tr[2]/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/div/div/section[3]/div/div/div[5]/div/div[2]/table/tbody/tr[2]/td/span</value>
   </webElementProperties>
</WebElementEntity>
