<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_SelectAll</name>
   <tag></tag>
   <elementGuidId>ca3af0e6-2c89-4506-8b2f-b9a684362959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[1]/div[2]/div/div/div[2]/div[1]/div[2]/div/div/span/div/div/ul/li[2]/a/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
