<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabelValue_SupplierPostalCode</name>
   <tag></tag>
   <elementGuidId>7730520a-e515-43ff-ad30-57214fc61269</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[1]/div[2]/div/div/div/section[1]/div/div/div[5]/div/div[1]/table/tbody/tr[4]/td/text()[6]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
