<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>unsatisfied_RatingValue</name>
   <tag></tag>
   <elementGuidId>8f64f796-d994-4c3b-812b-4b4f98bd23ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[4]/div/div[2]/table/tbody/tr[4]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
