<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>variants_02</name>
   <tag></tag>
   <elementGuidId>4de61bb4-93c6-450b-8eca-4c0a123fd561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[1]/div[2]/div[1]/div/div[3]/div[1]/div[1]/div/span[2]/span[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
