<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NEGO (B2C)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3b7215a4-ed2c-4e6d-9c1b-540dc9c18310</testSuiteGuid>
   <testCaseLink>
      <guid>7495a350-0513-4479-8047-9a0f1aae35ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Nego Scenario/Nego DiscFixed Charges/00_itemSearch</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5346b1f5-c132-4305-99d5-08b7ebaccf54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Nego Scenario/Nego DiscFixed Charges/01_buyerChat</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3480560b-dd7a-4309-ab39-39ef6dc67c0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Nego Scenario/Nego DiscFixed Charges/02_sellerCreateQuotation</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>eed25d48-d42d-466f-9c6a-cbc513200b4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Nego Scenario/Nego DiscFixed Charges/03_buyerCheckQuotation</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>59063bc4-33aa-4025-8ae8-599c060b6d67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot (B2C)/04_OnePageCheckout</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16a32727-9b94-48a5-ae9b-cc0ec2efd763</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a350c17-0c6a-41fd-beec-44e131e07a82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da7acb36-4daa-4272-8ef0-2990690d161a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06516336-4e46-4074-9b80-30f015eeccb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77ca883c-c2fb-4424-b7a3-0cc1489ab359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f805c378-58d1-4075-b5b3-a5bf85f38fbd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09857087-8daf-42c7-be34-cac212b55734</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6904e0dd-789b-4087-b896-97cceeb0e935</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b34eee5e-7c5f-4f83-908d-2da8116339ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63415c19-2bca-4945-ae95-09ac4969234d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot (B2C)/05_historyPageBuyer</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>60f964c2-7411-44b4-b61c-f4b568179980</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot (B2C)/06_historyPageSeller</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc15765d-f922-4da8-bd55-adccef484081</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
