<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SPOT OFF(B2B)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>cacb88a5-8614-4357-9940-ed8b500a5cd2</testSuiteGuid>
   <testCaseLink>
      <guid>8e476b99-2e5e-4b92-8a6d-1a616c7c3d90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot - Off (B2B)/01_searchItem</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>269d9b58-fb61-44f9-933c-23dadd22cb75</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2d80278-aa7d-4866-a82e-e6ac255f6b7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot - Off (B2B)/03_cartPage</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a61a1fac-99a3-406b-a0c5-7acddd4d8fb6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot - Off (B2B)/02_itemDetails</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>35a7908e-2698-4740-ac6b-8a2717cc9931</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot - Off (B2B)/04_OneRequisitionPage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c647ebe7-81c5-4ffe-be9b-4ea6957be24d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abb98010-df72-4834-80d3-628148b5874a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47eb1ee8-a8c6-439e-85e5-8d5ee8e663da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f75f2e42-4415-4b11-943d-33f9bbfe7847</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a70ffb3-0168-40b7-8837-27bf60879102</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>831e1521-eeb0-4cec-bd60-2217f4357abd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9782a04d-0c69-47c8-9d49-ac034ca04262</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c4a9b25-2785-4651-a288-39a7ed457e10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16e910a7-1579-42ac-8d70-7b9f1fa05eeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71bce126-c7b0-49af-9895-c9dd7a01e8e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>870363f8-81ea-48c6-ac93-718d50760c01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot - Off (B2B)/06_VerificationRequisitionPage</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a5b5932b-ee24-4e3a-a0e4-57beeb283c1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot - Off (B2B)/07_CreateGR</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>440f1caf-b8e4-4ac3-a176-4b03b6fe3c63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7076cfc-887b-4ed7-8118-678d7423d6fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be134d15-5671-445d-928c-0ea125169d1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67f6398c-f213-46fe-886b-4af25af5f6dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot - Off (B2B)/08_Invoice</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e967acea-f247-409b-ae44-c0b980f6f9d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SUPERBABY/BUYER/Checkout Flow/Spot - Off (B2B)/09_Payment</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
