<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabelValue_SellerEmail</name>
   <tag></tag>
   <elementGuidId>61f8787c-e240-44ce-a096-9a76a1265d03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[3]/div[2]/div/div[2]/div/div[2]/div[4]/div[2]/div[1]/div/div[2]/div[1]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/div[2]/div[4]/div[2]/div[1]/div/div[2]/div[1]/p</value>
   </webElementProperties>
</WebElementEntity>
