<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_AllCategories</name>
   <tag></tag>
   <elementGuidId>c650a18d-ed59-4e0c-9d8f-6ab2ed624eb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-section']/div[2]/div/ul/li[2]/div/div[2]/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[2]/div/ul/li[2]/div/div[2]/select[count(. | //select[(text() = 'All CategoriesCategory 01Category 02Category 03Category 04Category 05Category 06Category 07Category 08Category 09Category 10Category 11Category 12Category 13Category 14Category 15Category 16Category 17Category 18Category 19Category 20Category Name mAx 021!!@#$%^&amp;!Category EDITED' or . = 'All CategoriesCategory 01Category 02Category 03Category 04Category 05Category 06Category 07Category 08Category 09Category 10Category 11Category 12Category 13Category 14Category 15Category 16Category 17Category 18Category 19Category 20Category Name mAx 021!!@#$%^&amp;!Category EDITED')]) = count(//select[(text() = 'All CategoriesCategory 01Category 02Category 03Category 04Category 05Category 06Category 07Category 08Category 09Category 10Category 11Category 12Category 13Category 14Category 15Category 16Category 17Category 18Category 19Category 20Category Name mAx 021!!@#$%^&amp;!Category EDITED' or . = 'All CategoriesCategory 01Category 02Category 03Category 04Category 05Category 06Category 07Category 08Category 09Category 10Category 11Category 12Category 13Category 14Category 15Category 16Category 17Category 18Category 19Category 20Category Name mAx 021!!@#$%^&amp;!Category EDITED')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All CategoriesCategory 01Category 02Category 03Category 04Category 05Category 06Category 07Category 08Category 09Category 10Category 11Category 12Category 13Category 14Category 15Category 16Category 17Category 18Category 19Category 20Category Name mAx 021!!@#$%^&amp;!Category EDITED</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/div/div[2]/select</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-section']/div[2]/div/ul/li[2]/div/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTER/SIGN IN'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Cart'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
