<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_allCat_Text editor_NM</name>
   <tag></tag>
   <elementGuidId>8f44a6f7-a101-4403-933f-48243e81de06</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>allCat_Text editor_NMRich Text Editor, formattedText_118512-allCat_Texteditor_NM-zQtknI43mGEditor toolbarsDocument BoldKeyboard shortcut Ctrl+B ItalicKeyboard shortcut Ctrl+I UnderlineKeyboard shortcut Ctrl+U Strikethrough Subscript SuperscriptClipboard/Undo Paste as plain textKeyboard shortcut Ctrl+Shift+V Paste from Word UndoKeyboard shortcut Ctrl+Z RedoKeyboard shortcut Ctrl+YEditing Select AllParagraph Insert/Remove Numbered List Insert/Remove Bulleted List Decrease Indent Increase Indent Block Quote Align Left Center Align Right JustifyLinks LinkKeyboard shortcut Ctrl+K UnlinkInsert Image Table Insert Horizontal Line Smiley Insert Special CharacterStylesStylesStylesFormatNormalFontFontSizeSizeColors Text Color Background ColorPress ALT 0 for help◢</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customfields&quot;)/div[@class=&quot;col-md-6&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customfields']/div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='allCat_Text field_NM2'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='allCat_Text field_NM1'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[4]</value>
   </webElementXpaths>
</WebElementEntity>
