<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Buyer3</name>
   <tag></tag>
   <elementGuidId>db11a465-abe6-40fd-9612-6cbb691bf7f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div/div/div[2]/div/div[1]/div[1]/form/div/div/div[1]/div[2]/div/div/ul/li[5]/a/label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
