<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_lastLogin</name>
   <tag></tag>
   <elementGuidId>c4f3c75d-ec5e-4a0b-aa25-813b2b786710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;lastLogin&quot;)[count(. | //*[@id = 'lastLogin' and (text() = '24/06/2021 17:05:49' or . = '24/06/2021 17:05:49')]) = count(//*[@id = 'lastLogin' and (text() = '24/06/2021 17:05:49' or . = '24/06/2021 17:05:49')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastLogin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24/06/2021 17:05:49</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lastLogin&quot;)</value>
   </webElementProperties>
</WebElementEntity>
